#!/bin/sh
#=====================================================================
# EHMFILES  THE LIST OF ARTEFACTS THAT MAKE UP THE GOLDEN BASELINE,
#           SOURCED BY TOOLS/BASELINE.SH AND TOOLS/VERIFY.SH.
#
# ENGMAS/FLTLOG/FLTVAL/TRNMAS/ALRTMS/RULMAS/SVPLAN ARE THE MASTER FILES
# WRITTEN BY STEPS 010 TO 060.  SYSPRINT.TXT IS THE JOB PRINT FILE AND
# SYSERR.LOG IS THE ACCUMULATED DIAGNOSTIC FILE.
#
# THE CONTROL CARDS COPIED INTO WORK/ BY RUNEHM.SH (PARLIM, SHPSLT,
# EHMCTL) ARE INPUTS, NOT OUTPUTS, SO THEY ARE NOT BASELINED.  SO IS
# SYSERR.DAT, WHICH IS SCRATCHED AND REALLOCATED BY EVERY STEP.
#=====================================================================

EHM_FILES="SYSPRINT.TXT
SYSERR.LOG
ENGMAS.DAT
FLTLOG.DAT
FLTVAL.DAT
TRNMAS.DAT
ALRTMS.DAT
RULMAS.DAT
SVPLAN.DAT"
